apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-13T04:14:16Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "570"
  uid: 0cbc4e9e-45a8-42dc-8ebd-2b1e11ba6ab5
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.97.176.215
  clusterIPs:
  - 10.97.176.215
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32569
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}